import Head from 'next/head'
import {AppProps} from 'next/app'
import {GlobalStyles} from "../styles/GlobalStyles";
import React, {useState} from "react";
import {SearchProvider} from "../context/SearchContext";
import Script from "next/script";


function MyApp({Component, pageProps}: AppProps) {

    const [loadScript, setLoadScript] = useState(false)

    if (!loadScript) {
        return (
            <Script
                id="google-maps-js"
                src="https://maps.googleapis.com/maps/api/js?key=GOOGLE_KEY"
                onLoad={() => {
                    setLoadScript(true)
                }}
            />
        )
    }

    return (
        <>
            <Head>
                <title>Brickbro</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>

            </Head>
            <GlobalStyles/>
            <SearchProvider>
                <Component {...pageProps} />
            </SearchProvider>
        </>
    )
}

export default MyApp
